# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
#
# CodeRabbit Configuration - Example defaults
# This file is a partial example and may not include every valid configuration option.
# See the schema (above) for the complete list of supported keys and tools.
#

# General settings
language: "en-US"
tone_instructions: ""
early_access: false
enable_free_tier: true

reviews:
  # Review profile and behavior
  profile: "chill"
  request_changes_workflow: false

  # High-level summary settings
  high_level_summary: true
  high_level_summary_instructions: "In the high level summary, give a description of the langauges used, the frameworks and code patterns used, and then a brief description in 50 words or less."
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false

  # Auto title settings
  # auto_title_placeholder: "@coderabbitai"
  auto_title_placeholder: "[cr]"
  auto_title_instructions: ""

  # Review status and commit status
  review_status: true
  commit_status: true
  fail_commit_status: false

  # Walkthrough settings
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true

  # Issue and PR related settings
  assess_linked_issues: true
  related_issues: true
  related_prs: true

  # Labeling settings
  suggested_labels: true
  labeling_instructions: []
  auto_apply_labels: false

  # Path filtering and instructions
  path_filters: []
  path_instructions:
    # Go-specific instructions
    - path: "**/*.go"
      instructions: |
        Review Go code following these standards:
        - Use proper error handling with error wrapping using fmt.Errorf with %w verb
        - Ensure all public functions have godoc comments
        - Follow Go naming conventions (exported names start with capital letter)
        - Use context.Context for cancellation and timeouts in long-running operations
        - Prefer explicit error returns over panic
        - Use defer for cleanup operations
        - Validate input parameters and return descriptive errors
        - Consider concurrency safety for shared state

  # Auto review settings
  auto_review:
    enabled: true
    ignore_title_keywords: []
    drafts: false
    base_branches: []

  # Static analysis tools
  tools:
    # JavaScript/TypeScript
    eslint:
      enabled: true
    biome:
      enabled: true

    # Go
    golangci-lint:
      enabled: true

    # Python
    ruff:
      enabled: true
    pylint:
      enabled: true

    # Ruby
    rubocop:
      enabled: true

    # PHP
    phpstan:
      enabled: true
      level: default

    # Java/Kotlin
    pmd:
      enabled: true
    detekt:
      enabled: true

    # C/C++
    cppcheck:
      enabled: true

    # Rust
    clippy:
      enabled: true

    # Infrastructure
    hadolint:
      enabled: true
    yamllint:
      enabled: true
    shellcheck:
      enabled: true
    actionlint:
      enabled: true

    # Security
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    semgrep:
      enabled: true
    osvScanner:
      enabled: true

    # Documentation
    markdownlint:
      enabled: true
    languagetool:
      enabled: true
      level: default
      disabled_categories: []

    # Protocol Buffers
    buf:
      enabled: true

    # GitHub specific
    github-checks:
      enabled: true
      timeout_ms: 90000

chat:
  art: true
  auto_reply: true
  integrations:
    jira:
      usage: "enabled"
    linear:
      usage: "enabled"

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: "global"
  issues:
    scope: "global"
  jira:
    usage: "enabled"
    project_keys: []
  linear:
    usage: "enabled"
    team_keys: []
  pull_requests:
    scope: "global"
  mcp:
    usage: "enabled"
    disabled_servers: []

issue_enrichment:
  auto_enrich:
    enabled: true

code_generation:
  docstrings:
    language: "en-US"
    path_instructions: []
  unit_tests:
    path_instructions: []

