# Inherit settings from the Organization level and/or centralized `coderabbit` repo if it exists.
inheritance: true

# Customize your own repos with `path_instructions` that tune how CodeRabbit behaves and what issues it should find
reviews:
  path_instructions:
    - path: '**/*'
      instructions: validate changed files in this branch satisfy the acceptance criteria of a ticket mentioned. for example, if a ticket mentions solving kan-19, go to the kan board and verify it does

